<?php defined('ByShopKJYP') or exit('Access Invalid!'); return array (
  1 => 
  array (
    'gc_id' => '1',
    'gc_name' => '奶粉专区',
    'gc_url' => 'http://www.kjyp360.com/special/?spc_id=1',
    'type_id' => '3',
    'type_name' => '罐数',
    'gc_parent_id' => '0',
    'commis_rate' => '0',
    'gc_sort' => '1',
    'gc_title' => '{name}-跨境优品',
    'gc_keywords' => '{name}',
    'gc_description' => '跨境优品专注全球精选母婴用品特卖,各类母婴用品、辅食、纸尿裤全场包邮',
    'gc_virtual' => '0',
    'gc_show' => '1',
    'show_type' => '2',
    'cn_adv2_link' => '',
    'cn_alias' => '',
    'cn_adv1_link' => '',
    'cn_brands' => 
    array (
    ),
    'cn_classs' => 
    array (
      0 => 
      array (
        'gc_id' => '33',
        'gc_name' => '澳洲A2',
        'gc_url' => 'http://www.kjyp360.com/special/?spc_id=103',
        'type_id' => '3',
        'type_name' => '罐数',
        'gc_parent_id' => '1',
        'commis_rate' => '0',
        'gc_sort' => '2',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '2',
      ),
      1 => 
      array (
        'gc_id' => '35',
        'gc_name' => '英国爱他美',
        'gc_url' => 'http://www.kjyp360.com/special/?spc_id=121',
        'type_id' => '3',
        'type_name' => '罐数',
        'gc_parent_id' => '1',
        'commis_rate' => '0',
        'gc_sort' => '3',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '2',
      ),
    ),
    'class2' => 
    array (
      107 => 
      array (
        'gc_id' => '107',
        'gc_name' => '荷兰美素',
        'gc_url' => 'http://www.kjyp360.com/special/?spc_id=91',
        'type_id' => '3',
        'type_name' => '罐数',
        'gc_parent_id' => '1',
        'commis_rate' => '0',
        'gc_sort' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '2',
      ),
      263 => 
      array (
        'gc_id' => '263',
        'gc_name' => '惠氏S-26',
        'gc_url' => '',
        'type_id' => '3',
        'type_name' => '罐数',
        'gc_parent_id' => '1',
        'commis_rate' => '0',
        'gc_sort' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '2',
      ),
      275 => 
      array (
        'gc_id' => '275',
        'gc_name' => '德国爱他美白金版',
        'gc_url' => '',
        'type_id' => '3',
        'type_name' => '罐数',
        'gc_parent_id' => '1',
        'commis_rate' => '0',
        'gc_sort' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '2',
      ),
      277 => 
      array (
        'gc_id' => '277',
        'gc_name' => '澳洲爱他美白金版',
        'gc_url' => '',
        'type_id' => '3',
        'type_name' => '罐数',
        'gc_parent_id' => '1',
        'commis_rate' => '0',
        'gc_sort' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '2',
      ),
      34 => 
      array (
        'gc_id' => '34',
        'gc_name' => '英国牛栏',
        'gc_url' => 'http://www.kjyp360.com/special/?spc_id=93',
        'type_id' => '3',
        'type_name' => '罐数',
        'gc_parent_id' => '1',
        'commis_rate' => '0',
        'gc_sort' => '1',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '2',
      ),
      33 => 
      array (
        'gc_id' => '33',
        'gc_name' => '澳洲A2',
        'gc_url' => 'http://www.kjyp360.com/special/?spc_id=103',
        'type_id' => '3',
        'type_name' => '罐数',
        'gc_parent_id' => '1',
        'commis_rate' => '0',
        'gc_sort' => '2',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '2',
      ),
      35 => 
      array (
        'gc_id' => '35',
        'gc_name' => '英国爱他美',
        'gc_url' => 'http://www.kjyp360.com/special/?spc_id=121',
        'type_id' => '3',
        'type_name' => '罐数',
        'gc_parent_id' => '1',
        'commis_rate' => '0',
        'gc_sort' => '3',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '2',
      ),
      149 => 
      array (
        'gc_id' => '149',
        'gc_name' => '荷兰牛栏',
        'gc_url' => 'http://www.kjyp360.com/special/?spc_id=137',
        'type_id' => '3',
        'type_name' => '罐数',
        'gc_parent_id' => '1',
        'commis_rate' => '0',
        'gc_sort' => '5',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '2',
      ),
      151 => 
      array (
        'gc_id' => '151',
        'gc_name' => '德国爱他美',
        'gc_url' => 'http://www.kjyp360.com/brand-35-0-0-0-0-0-0.html',
        'type_id' => '3',
        'type_name' => '罐数',
        'gc_parent_id' => '1',
        'commis_rate' => '0',
        'gc_sort' => '6',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '2',
      ),
      155 => 
      array (
        'gc_id' => '155',
        'gc_name' => '德国喜宝',
        'gc_url' => 'http://www.kjyp360.com/brand-31-0-0-0-0-0-0.html',
        'type_id' => '3',
        'type_name' => '罐数',
        'gc_parent_id' => '1',
        'commis_rate' => '0',
        'gc_sort' => '8',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '2',
      ),
      157 => 
      array (
        'gc_id' => '157',
        'gc_name' => '澳洲爱他美精装',
        'gc_url' => 'http://www.kjyp360.com/brand-307-0-0-0-0-0-0.html',
        'type_id' => '3',
        'type_name' => '罐数',
        'gc_parent_id' => '1',
        'commis_rate' => '0',
        'gc_sort' => '9',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '2',
      ),
      159 => 
      array (
        'gc_id' => '159',
        'gc_name' => '德国特福芬',
        'gc_url' => 'http://www.kjyp360.com/brand-33-0-0-0-0-0-0.html',
        'type_id' => '3',
        'type_name' => '罐数',
        'gc_parent_id' => '1',
        'commis_rate' => '0',
        'gc_sort' => '10',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '2',
      ),
      163 => 
      array (
        'gc_id' => '163',
        'gc_name' => '荷兰佳贝艾特',
        'gc_url' => 'http://www.kjyp360.com/brand-231-0-0-0-0-0-0.html',
        'type_id' => '3',
        'type_name' => '罐数',
        'gc_parent_id' => '1',
        'commis_rate' => '0',
        'gc_sort' => '12',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '2',
      ),
      255 => 
      array (
        'gc_id' => '255',
        'gc_name' => '澳洲贝拉米',
        'gc_url' => 'http://www.kjyp360.com/brand-235-0-0-0-0-0-0.html',
        'type_id' => '3',
        'type_name' => '罐数',
        'gc_parent_id' => '1',
        'commis_rate' => '0',
        'gc_sort' => '12',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '2',
      ),
      109 => 
      array (
        'gc_id' => '109',
        'gc_name' => '新西兰可瑞康羊奶',
        'gc_url' => 'http://www.kjyp360.com/special/?spc_id=89',
        'type_id' => '3',
        'type_name' => '罐数',
        'gc_parent_id' => '1',
        'commis_rate' => '0',
        'gc_sort' => '14',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '2',
      ),
    ),
  ),
  2 => 
  array (
    'gc_id' => '2',
    'gc_name' => '家居生活',
    'gc_url' => 'http://www.kjyp360.com',
    'type_id' => '0',
    'type_name' => '',
    'gc_parent_id' => '0',
    'commis_rate' => '0',
    'gc_sort' => '2',
    'gc_title' => '{name}-跨境优品',
    'gc_keywords' => '{name}',
    'gc_description' => '跨境优品专注全球精选母婴用品特卖,各类母婴用品、辅食、纸尿裤全场包邮',
    'gc_virtual' => '0',
    'gc_show' => '1',
    'show_type' => '1',
    'cn_adv2_link' => '',
    'cn_alias' => '',
    'cn_adv1_link' => '',
    'cn_brands' => 
    array (
    ),
    'cn_classs' => 
    array (
      0 => 
      array (
        'gc_id' => '163',
        'gc_name' => '荷兰佳贝艾特',
        'gc_url' => 'http://www.kjyp360.com/brand-231-0-0-0-0-0-0.html',
        'type_id' => '3',
        'type_name' => '罐数',
        'gc_parent_id' => '1',
        'commis_rate' => '0',
        'gc_sort' => '12',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '2',
      ),
      1 => 
      array (
        'gc_id' => '193',
        'gc_name' => '春雨',
        'gc_url' => '',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '5',
        'commis_rate' => '0',
        'gc_sort' => '6',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
    ),
    'class2' => 
    array (
      125 => 
      array (
        'gc_id' => '125',
        'gc_name' => '个人洗护',
        'gc_url' => 'http://www.kjyp360.com/special/?spc_id=107',
        'type_id' => '19',
        'type_name' => '',
        'gc_parent_id' => '2',
        'commis_rate' => '0',
        'gc_sort' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      229 => 
      array (
        'gc_id' => '229',
        'gc_name' => '眼罩口罩',
        'gc_url' => '',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '2',
        'commis_rate' => '0',
        'gc_sort' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      231 => 
      array (
        'gc_id' => '231',
        'gc_name' => '沐浴清洁',
        'gc_url' => '',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '2',
        'commis_rate' => '0',
        'gc_sort' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      227 => 
      array (
        'gc_id' => '227',
        'gc_name' => '卫生巾系列',
        'gc_url' => 'http://www.kjyp360.com/special/?spc_id=147',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '2',
        'commis_rate' => '0',
        'gc_sort' => '1',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      69 => 
      array (
        'gc_id' => '69',
        'gc_name' => '家居日用',
        'gc_url' => 'http://www.kjyp360.com/special/?spc_id=111',
        'type_id' => '25',
        'type_name' => '只',
        'gc_parent_id' => '2',
        'commis_rate' => '0',
        'gc_sort' => '2',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      71 => 
      array (
        'gc_id' => '71',
        'gc_name' => '女性护理',
        'gc_url' => 'http://www.kjyp360.com/special/?spc_id=113',
        'type_id' => '21',
        'type_name' => '包数',
        'gc_parent_id' => '2',
        'commis_rate' => '0',
        'gc_sort' => '3',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      241 => 
      array (
        'gc_id' => '241',
        'gc_name' => '洗发护发',
        'gc_url' => '',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '2',
        'commis_rate' => '0',
        'gc_sort' => '3',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      133 => 
      array (
        'gc_id' => '133',
        'gc_name' => '滤水壶/滤芯',
        'gc_url' => '',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '2',
        'commis_rate' => '0',
        'gc_sort' => '4',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      219 => 
      array (
        'gc_id' => '219',
        'gc_name' => '牙刷',
        'gc_url' => '',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '2',
        'commis_rate' => '0',
        'gc_sort' => '5',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      221 => 
      array (
        'gc_id' => '221',
        'gc_name' => '牙膏',
        'gc_url' => '',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '2',
        'commis_rate' => '0',
        'gc_sort' => '6',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      223 => 
      array (
        'gc_id' => '223',
        'gc_name' => '漱口水',
        'gc_url' => '',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '2',
        'commis_rate' => '0',
        'gc_sort' => '7',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      141 => 
      array (
        'gc_id' => '141',
        'gc_name' => '家居清洁',
        'gc_url' => '',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '2',
        'commis_rate' => '0',
        'gc_sort' => '8',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      143 => 
      array (
        'gc_id' => '143',
        'gc_name' => '衣服清洁',
        'gc_url' => '',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '2',
        'commis_rate' => '0',
        'gc_sort' => '9',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      145 => 
      array (
        'gc_id' => '145',
        'gc_name' => '厨房清洁',
        'gc_url' => '',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '2',
        'commis_rate' => '0',
        'gc_sort' => '10',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      245 => 
      array (
        'gc_id' => '245',
        'gc_name' => '手足清洁',
        'gc_url' => '',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '2',
        'commis_rate' => '0',
        'gc_sort' => '10',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      147 => 
      array (
        'gc_id' => '147',
        'gc_name' => '厕所卫浴清洁',
        'gc_url' => '',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '2',
        'commis_rate' => '0',
        'gc_sort' => '11',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      131 => 
      array (
        'gc_id' => '131',
        'gc_name' => '杯子',
        'gc_url' => '',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '2',
        'commis_rate' => '0',
        'gc_sort' => '12',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      135 => 
      array (
        'gc_id' => '135',
        'gc_name' => '锅具刀具小家电',
        'gc_url' => 'http://www.kjyp360.com/special/?spc_id=157',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '2',
        'commis_rate' => '0',
        'gc_sort' => '15',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
    ),
  ),
  101 => 
  array (
    'gc_id' => '101',
    'gc_name' => '母婴用品',
    'gc_url' => 'http://www.kjyp360.com/special/?spc_id=37',
    'type_id' => '0',
    'type_name' => '',
    'gc_parent_id' => '0',
    'commis_rate' => '0',
    'gc_sort' => '3',
    'gc_title' => '',
    'gc_keywords' => '',
    'gc_description' => '',
    'gc_virtual' => '0',
    'gc_show' => '1',
    'show_type' => '1',
    'class2' => 
    array (
      127 => 
      array (
        'gc_id' => '127',
        'gc_name' => '纸尿裤/拉拉裤',
        'gc_url' => 'http://www.kjyp360.com/special/?spc_id=3',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '101',
        'commis_rate' => '0',
        'gc_sort' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      239 => 
      array (
        'gc_id' => '239',
        'gc_name' => '宝宝零食',
        'gc_url' => '',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '101',
        'commis_rate' => '0',
        'gc_sort' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      249 => 
      array (
        'gc_id' => '249',
        'gc_name' => '孕妈必备',
        'gc_url' => '',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '101',
        'commis_rate' => '0',
        'gc_sort' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      251 => 
      array (
        'gc_id' => '251',
        'gc_name' => '日常护理',
        'gc_url' => '',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '101',
        'commis_rate' => '0',
        'gc_sort' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      261 => 
      array (
        'gc_id' => '261',
        'gc_name' => '座椅推车',
        'gc_url' => '',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '101',
        'commis_rate' => '0',
        'gc_sort' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      117 => 
      array (
        'gc_id' => '117',
        'gc_name' => '宝宝辅食',
        'gc_url' => 'http://www.kjyp360.com/special/?spc_id=127',
        'type_id' => '17',
        'type_name' => '',
        'gc_parent_id' => '101',
        'commis_rate' => '0',
        'gc_sort' => '1',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      119 => 
      array (
        'gc_id' => '119',
        'gc_name' => '宝宝洗护',
        'gc_url' => 'http://www.kjyp360.com/special/?spc_id=129',
        'type_id' => '31',
        'type_name' => '盒',
        'gc_parent_id' => '101',
        'commis_rate' => '0',
        'gc_sort' => '2',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      121 => 
      array (
        'gc_id' => '121',
        'gc_name' => '宝宝用品',
        'gc_url' => 'http://www.kjyp360.com/special/?spc_id=131',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '101',
        'commis_rate' => '0',
        'gc_sort' => '3',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      209 => 
      array (
        'gc_id' => '209',
        'gc_name' => '奶瓶奶嘴',
        'gc_url' => '',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '101',
        'commis_rate' => '0',
        'gc_sort' => '4',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      207 => 
      array (
        'gc_id' => '207',
        'gc_name' => '牙膏牙刷',
        'gc_url' => '',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '101',
        'commis_rate' => '0',
        'gc_sort' => '5',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      173 => 
      array (
        'gc_id' => '173',
        'gc_name' => '辅食泥',
        'gc_url' => '',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '101',
        'commis_rate' => '0',
        'gc_sort' => '6',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      175 => 
      array (
        'gc_id' => '175',
        'gc_name' => '米粉米糊',
        'gc_url' => '',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '101',
        'commis_rate' => '0',
        'gc_sort' => '7',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      181 => 
      array (
        'gc_id' => '181',
        'gc_name' => '营养保健',
        'gc_url' => 'http://www.kjyp360.com/special/?spc_id=97',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '101',
        'commis_rate' => '0',
        'gc_sort' => '9',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      165 => 
      array (
        'gc_id' => '165',
        'gc_name' => '日本花王',
        'gc_url' => '',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '101',
        'commis_rate' => '0',
        'gc_sort' => '10',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      237 => 
      array (
        'gc_id' => '237',
        'gc_name' => '湿巾',
        'gc_url' => '',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '101',
        'commis_rate' => '0',
        'gc_sort' => '10',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      247 => 
      array (
        'gc_id' => '247',
        'gc_name' => '益智玩具',
        'gc_url' => '',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '101',
        'commis_rate' => '0',
        'gc_sort' => '10',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      167 => 
      array (
        'gc_id' => '167',
        'gc_name' => '日本尤妮佳',
        'gc_url' => '',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '101',
        'commis_rate' => '0',
        'gc_sort' => '11',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      169 => 
      array (
        'gc_id' => '169',
        'gc_name' => '日本大王',
        'gc_url' => '',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '101',
        'commis_rate' => '0',
        'gc_sort' => '12',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      171 => 
      array (
        'gc_id' => '171',
        'gc_name' => 'Zwitsal',
        'gc_url' => 'http://www.kjyp360.com/brand-55-0-0-0-0-0-0.html',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '101',
        'commis_rate' => '0',
        'gc_sort' => '13',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      211 => 
      array (
        'gc_id' => '211',
        'gc_name' => '清洁消毒',
        'gc_url' => '',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '101',
        'commis_rate' => '0',
        'gc_sort' => '14',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      259 => 
      array (
        'gc_id' => '259',
        'gc_name' => '可么多么',
        'gc_url' => 'http://www.kjyp360.com/special/?spc_id=163',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '101',
        'commis_rate' => '0',
        'gc_sort' => '15',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
    ),
  ),
  5 => 
  array (
    'gc_id' => '5',
    'gc_name' => '个护美妆',
    'gc_url' => 'http://www.kjyp360.com/special/?spc_id=47',
    'type_id' => '0',
    'type_name' => '',
    'gc_parent_id' => '0',
    'commis_rate' => '0',
    'gc_sort' => '4',
    'gc_title' => '{name}-跨境优品',
    'gc_keywords' => '{name}',
    'gc_description' => '跨境优品专注全球精选母婴用品特卖,各类母婴用品、辅食、纸尿裤全场包邮',
    'gc_virtual' => '0',
    'gc_show' => '1',
    'show_type' => '1',
    'class2' => 
    array (
      267 => 
      array (
        'gc_id' => '267',
        'gc_name' => 'SANA豆乳',
        'gc_url' => '',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '5',
        'commis_rate' => '0',
        'gc_sort' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      269 => 
      array (
        'gc_id' => '269',
        'gc_name' => 'LANCÔME兰蔻',
        'gc_url' => '',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '5',
        'commis_rate' => '0',
        'gc_sort' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      271 => 
      array (
        'gc_id' => '271',
        'gc_name' => '雅诗兰黛',
        'gc_url' => '',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '5',
        'commis_rate' => '0',
        'gc_sort' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      273 => 
      array (
        'gc_id' => '273',
        'gc_name' => 'Clinique倩碧',
        'gc_url' => '',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '5',
        'commis_rate' => '0',
        'gc_sort' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      279 => 
      array (
        'gc_id' => '279',
        'gc_name' => 'VDL提亮液',
        'gc_url' => '',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '5',
        'commis_rate' => '0',
        'gc_sort' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      281 => 
      array (
        'gc_id' => '281',
        'gc_name' => '英国Boots',
        'gc_url' => '',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '5',
        'commis_rate' => '0',
        'gc_sort' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      283 => 
      array (
        'gc_id' => '283',
        'gc_name' => '澳大利亚Sukin',
        'gc_url' => '',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '5',
        'commis_rate' => '0',
        'gc_sort' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      285 => 
      array (
        'gc_id' => '285',
        'gc_name' => 'SNP',
        'gc_url' => '',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '5',
        'commis_rate' => '0',
        'gc_sort' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      193 => 
      array (
        'gc_id' => '193',
        'gc_name' => '春雨',
        'gc_url' => '',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '5',
        'commis_rate' => '0',
        'gc_sort' => '6',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      195 => 
      array (
        'gc_id' => '195',
        'gc_name' => '水光',
        'gc_url' => 'http://www.kjyp360.com/brand-247-0-0-0-0-0-0.html',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '5',
        'commis_rate' => '0',
        'gc_sort' => '7',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      197 => 
      array (
        'gc_id' => '197',
        'gc_name' => 'Royal Nectar',
        'gc_url' => '',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '5',
        'commis_rate' => '0',
        'gc_sort' => '8',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      199 => 
      array (
        'gc_id' => '199',
        'gc_name' => '韩国伊思',
        'gc_url' => 'http://www.kjyp360.com/brand-275-0-0-0-0-0-0.html',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '5',
        'commis_rate' => '0',
        'gc_sort' => '9',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      201 => 
      array (
        'gc_id' => '201',
        'gc_name' => 'CASMARA卡曼',
        'gc_url' => '',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '5',
        'commis_rate' => '0',
        'gc_sort' => '10',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      203 => 
      array (
        'gc_id' => '203',
        'gc_name' => 'ne\'Kur',
        'gc_url' => '',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '5',
        'commis_rate' => '0',
        'gc_sort' => '11',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      205 => 
      array (
        'gc_id' => '205',
        'gc_name' => 'Re’au莱奥',
        'gc_url' => '',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '5',
        'commis_rate' => '0',
        'gc_sort' => '12',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
    ),
  ),
  4 => 
  array (
    'gc_id' => '4',
    'gc_name' => '营养保健',
    'gc_url' => 'http://www.kjyp360.com/special/?spc_id=87',
    'type_id' => '0',
    'type_name' => '',
    'gc_parent_id' => '0',
    'commis_rate' => '0',
    'gc_sort' => '5',
    'gc_title' => '{name}-跨境优品',
    'gc_keywords' => '{name}',
    'gc_description' => '跨境优品专注全球精选母婴用品特卖,各类母婴用品、辅食、纸尿裤全场包邮',
    'gc_virtual' => '0',
    'gc_show' => '1',
    'show_type' => '1',
    'class2' => 
    array (
      58 => 
      array (
        'gc_id' => '58',
        'gc_name' => '营养补充',
        'gc_url' => 'http://www.kjyp360.com/special/?spc_id=97',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '4',
        'commis_rate' => '0',
        'gc_sort' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      129 => 
      array (
        'gc_id' => '129',
        'gc_name' => '孕妈必备',
        'gc_url' => '',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '4',
        'commis_rate' => '0',
        'gc_sort' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      213 => 
      array (
        'gc_id' => '213',
        'gc_name' => '改善贫血',
        'gc_url' => '',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '4',
        'commis_rate' => '0',
        'gc_sort' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      59 => 
      array (
        'gc_id' => '59',
        'gc_name' => '调理免疫',
        'gc_url' => 'http://www.kjyp360.com/special/?spc_id=99',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '4',
        'commis_rate' => '0',
        'gc_sort' => '1',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      111 => 
      array (
        'gc_id' => '111',
        'gc_name' => '美容美体',
        'gc_url' => 'http://www.kjyp360.com/special/?spc_id=101',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '4',
        'commis_rate' => '0',
        'gc_sort' => '2',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
    ),
  ),
  6 => 
  array (
    'gc_id' => '6',
    'gc_name' => '全球直邮',
    'gc_url' => '',
    'type_id' => '0',
    'type_name' => '',
    'gc_parent_id' => '0',
    'commis_rate' => '0',
    'gc_sort' => '6',
    'gc_title' => '{name}-跨境优品',
    'gc_keywords' => '{name}',
    'gc_description' => '跨境优品专注全球精选母婴用品特卖,各类母婴用品、辅食、纸尿裤全场包邮',
    'gc_virtual' => '0',
    'gc_show' => '1',
    'show_type' => '1',
    'class2' => 
    array (
      87 => 
      array (
        'gc_id' => '87',
        'gc_name' => '母婴专区',
        'gc_url' => 'http://www.kjyp360.com/special/?spc_id=83',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '6',
        'commis_rate' => '0',
        'gc_sort' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
        'class3' => 
        array (
          91 => 
          array (
            'gc_id' => '91',
            'gc_name' => '奶粉',
            'gc_url' => '',
            'type_id' => '33',
            'type_name' => '直邮奶粉',
            'gc_parent_id' => '87',
            'commis_rate' => '0',
            'gc_sort' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
            'gc_virtual' => '0',
            'gc_show' => '1',
            'show_type' => '1',
          ),
          95 => 
          array (
            'gc_id' => '95',
            'gc_name' => '母婴用品',
            'gc_url' => '',
            'type_id' => '0',
            'type_name' => '',
            'gc_parent_id' => '87',
            'commis_rate' => '0',
            'gc_sort' => '0',
            'gc_title' => '',
            'gc_keywords' => '',
            'gc_description' => '',
            'gc_virtual' => '0',
            'gc_show' => '1',
            'show_type' => '1',
          ),
        ),
      ),
      97 => 
      array (
        'gc_id' => '97',
        'gc_name' => '家居个护',
        'gc_url' => 'http://www.kjyp360.com/special/?spc_id=85',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '6',
        'commis_rate' => '0',
        'gc_sort' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
      99 => 
      array (
        'gc_id' => '99',
        'gc_name' => '营养保健',
        'gc_url' => 'http://www.kjyp360.com/special/?spc_id=87',
        'type_id' => '0',
        'type_name' => '',
        'gc_parent_id' => '6',
        'commis_rate' => '0',
        'gc_sort' => '0',
        'gc_title' => '',
        'gc_keywords' => '',
        'gc_description' => '',
        'gc_virtual' => '0',
        'gc_show' => '1',
        'show_type' => '1',
      ),
    ),
  ),
);